Taks 12 validation
KamilMr/task-tracker pull request #10
Opened 2024-10-28 22:06 UTC by fitmariusz

Completion add validation under Create and edit project name. Change in files: project.js and validation.js

2024-10-29 09:52 UTC, KamilMr requested changes
Ładnie, małe poprawki i mergujemy :D

2024-10-29 09:52 UTC, KamilMr commented on src/commands/project.js
> +      return resp;
Tutaj zmień na `true`.  W takim stanie nie uda się dokonać zmiany.

2024-10-29 09:52 UTC, KamilMr commented on validation.js
> +    console.log(err)
Dla środowiska dev to ma sens natomiast w produkcji już nie. Dodasz komentarz w ramach tego PR:

// TODO: handle console.logs in production properly

2024-10-29 09:52 UTC, KamilMr commented on validation.js
> +const projectSchema = string().min(3).max(20).required();
Zostańmy przy `min(2)`

2024-10-29 09:52 UTC, KamilMr commented on validation.js
> +const projectSchema = string().min(3).max(20).required();
Oraz max(24) gdyż baza danych na to pozwala. 

` table.string('name', 24).notNullable();`

2024-10-29 20:22 UTC, fitmariusz commented
I have made changes to the CREATE and EDIT PROJECT validation according to the comments

2024-10-30 08:54 UTC, KamilMr commented on validation.js
> +const projectSchema = string().min(3).max(24).required();
```suggestion
const projectSchema = string().min(2).max(24).required();
```

2024-10-30 08:58 UTC, KamilMr approved these changes
Nicely done. :) 
One tip for future is to have shorter commit messages. The norm for one message is max 80 characters length.

2024-10-30 08:59 UTC, merged