Add confirmation delete project and client
KamilMr/task-tracker pull request #16
Opened 2024-11-04 22:21 UTC by fitmariusz

Create confirmation after Delete Project and Client.

2024-11-05 06:59 UTC, KamilMr requested changes
Hej, 
Almost there. 
Few things to change inside pull request. :)

2024-11-05 06:59 UTC, KamilMr commented on src/commands/client.js
> +  if(decision.toLowerCase()==='yes' | decision.toLowerCase()==='y')
You should use `||` instead of `|`.

2024-11-05 06:59 UTC, KamilMr commented on src/commands/client.js
> +  if(decision.toLowerCase()==='yes' | decision.toLowerCase()==='y')
Use spaces between elements. For example: 
```
if (decision === 'yes' || decision === 'y') 
```

2024-11-05 06:59 UTC, KamilMr commented on src/commands/client.js
> +  if(decision.toLowerCase()==='yes' | decision.toLowerCase()==='y')
When you use `if` statement have `{` on the same line as if - if possible.

2024-11-05 06:59 UTC, KamilMr commented on src/commands/project.js
> +    console.log('Project delete..')
Don't need that console.log

2024-11-05 06:59 UTC, KamilMr commented on src/commands/project.js
> +  if(decision.toLowerCase()==='yes' | decision.toLowerCase()==='y')
Previous comments applies to this place as well

2024-11-05 06:59 UTC, KamilMr commented on src/commands/client.js
> +  const decision = await inquirer.input({
`confirmation` makes more sense?

2024-11-05 06:59 UTC, KamilMr commented on src/commands/client.js
> +  return true;
I think returning true does not change anything, does it?

2024-11-06 06:47 UTC, KamilMr commented on src/commands/client.js
> +  if(decision.toLowerCase()==='yes' | decision.toLowerCase()==='y')
- [ ] Also here force user user to write only:  yes, y, no, n 

At the moment when he types something else, it is also valid.

2024-11-08 00:24 UTC, fitmariusz commented
Hi I Addition of validation during confirmation of PROJECT DELETE and CLIENT DELETE

2024-11-08 19:19 UTC, KamilMr commented on src/commands/client.js
> +  if(confirmation.toLowerCase()==='yes' || confirmation.toLowerCase()==='y')
```suggestion
  if (confirmation.toLowerCase() === 'yes' || confirmation.toLowerCase () === 'y' )
```

2024-11-08 19:23 UTC, merged